import { Inter } from 'next/font/google';
import './globals.css';
import Naver from '@/Compoment/Naver/Naver';
import Footer from '@/Compoment/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-screen-xl mx-auto">
          <Naver></Naver>
          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
